apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: '2018-10-30T16:58:39Z'
  labels:
    app: nexus3
  name: nexus-registry
spec:
  ports:
    - port: 5000
  selector:
    deploymentconfig: nexus3
