apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: user7-tasks-prod
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 6
    labels:
      app: tasks-blue
    name: tasks-blue
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: tasks-blue
      deploymentconfig: tasks-blue
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: tasks-blue
          deploymentconfig: tasks-blue
      spec:
        containers:
        - image: docker-registry.default.svc:5000/user7-tasks-dev/tasks:6.4.0-RELEASE
          imagePullPolicy: IfNotPresent
          name: tasks-blue
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /opt/eap/standalone/configuration/application-users.properties
            name: jboss-config
            subPath: application-users.properties
          - mountPath: /opt/eap/standalone/configuration/application-roles.properties
            name: jboss-config1
            subPath: application-roles.properties
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: tasks-blue-config
          name: jboss-config
        - configMap:
            defaultMode: 420
            name: tasks-blue-config
          name: jboss-config1
    test: false
    triggers: []
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 9
    labels:
      app: tasks-green
    name: tasks-green
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: tasks-green
      deploymentconfig: tasks-green
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: tasks-green
          deploymentconfig: tasks-green
      spec:
        containers:
        - image: docker-registry.default.svc:5000/user7-tasks-dev/tasks:6.4.0-RELEASE
          imagePullPolicy: IfNotPresent
          name: tasks-green
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /opt/eap/standalone/configuration/application-users.properties
            name: jboss-config
            subPath: application-users.properties
          - mountPath: /opt/eap/standalone/configuration/application-roles.properties
            name: jboss-config1
            subPath: application-roles.properties
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: tasks-green-config
          name: jboss-config
        - configMap:
            defaultMode: 420
            name: tasks-green-config
          name: jboss-config1
    test: false
    triggers: []
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: tasks-blue
    name: tasks
  spec:
    host: tasks-user7-tasks-prod.apps.4f28.openshift.opentlc.com
    port:
      targetPort: 8080
    to:
      kind: Service
      name: tasks-blue
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2018-11-01T15:33:36Z
        status: "True"
        type: Admitted
      host: tasks-user7-tasks-prod.apps.4f28.openshift.opentlc.com
      routerName: router
      wildcardPolicy: None
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/image.dockerRepositoryCheck: 2018-11-01T15:32:08Z
    creationTimestamp: null
    generation: 2
    name: tasks-blue
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/image.dockerRepositoryCheck: 2018-11-01T15:32:52Z
    creationTimestamp: null
    generation: 2
    name: tasks-green
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: tasks-blue
    name: tasks-blue
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: tasks-blue
      deploymentconfig: tasks-blue
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: tasks-green
    name: tasks-green
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: tasks-green
      deploymentconfig: tasks-green
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  data:
    application-roles.properties: |
      #
      # Properties declaration of users roles for the realm 'ApplicationRealm' which is the default realm
      # for application services on a new installation.
      #
      # This includes the following protocols: remote ejb, remote jndi, web, remote jms
      #
      # Users can be added to this properties file at any time, updates after the server has started
      # will be automatically detected.
      #
      # The format of this file is as follows: -
      # username=role1,role2,role3
      #
      # A utility script is provided which can be executed from the bin folder to add the users: -
      # - Linux
      #  bin/add-user.sh
      #
      # - Windows
      #  bin\add-user.bat
      #
      # The following illustrates how an admin user could be defined.
      #
      #admin=PowerUser,BillingAdmin,
      #guest=guest
      redhat=guest
    application-users.properties: |
      #
      # Properties declaration of users for the realm 'ApplicationRealm' which is the default realm
      # for application services on a new installation.
      #
      # This includes the following protocols: remote ejb, remote jndi, web, remote jms
      #
      # Users can be added to this properties file at any time, updates after the server has started
      # will be automatically detected.
      #
      # The format of this realm is as follows: -
      # username=HEX( MD5( username ':' realm ':' password))
      #
      # A utility script is provided which can be executed from the bin folder to add the users: -
      # - Linux
      #  bin/add-user.sh
      #
      # - Windows
      #  bin\add-user.bat
      #
      #$REALM_NAME=ApplicationRealm$ This line is used by the add-user utility to identify the realm name already used in this file.
      #
      # The following illustrates how an admin user could be defined, this
      # is for illustration only and does not correspond to a usable password.
      #
      #admin=2a0923285184943425d1f53ddd58ec7a
      redhat=a61461431d8a3a52ea041ea5d25dcbc2
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    name: tasks-blue-config
- apiVersion: v1
  data:
    application-roles.properties: |
      #
      # Properties declaration of users roles for the realm 'ApplicationRealm' which is the default realm
      # for application services on a new installation.
      #
      # This includes the following protocols: remote ejb, remote jndi, web, remote jms
      #
      # Users can be added to this properties file at any time, updates after the server has started
      # will be automatically detected.
      #
      # The format of this file is as follows: -
      # username=role1,role2,role3
      #
      # A utility script is provided which can be executed from the bin folder to add the users: -
      # - Linux
      #  bin/add-user.sh
      #
      # - Windows
      #  bin\add-user.bat
      #
      # The following illustrates how an admin user could be defined.
      #
      #admin=PowerUser,BillingAdmin,
      #guest=guest
      redhat=guest
    application-users.properties: |
      #
      # Properties declaration of users for the realm 'ApplicationRealm' which is the default realm
      # for application services on a new installation.
      #
      # This includes the following protocols: remote ejb, remote jndi, web, remote jms
      #
      # Users can be added to this properties file at any time, updates after the server has started
      # will be automatically detected.
      #
      # The format of this realm is as follows: -
      # username=HEX( MD5( username ':' realm ':' password))
      #
      # A utility script is provided which can be executed from the bin folder to add the users: -
      # - Linux
      #  bin/add-user.sh
      #
      # - Windows
      #  bin\add-user.bat
      #
      #$REALM_NAME=ApplicationRealm$ This line is used by the add-user utility to identify the realm name already used in this file.
      #
      # The following illustrates how an admin user could be defined, this
      # is for illustration only and does not correspond to a usable password.
      #
      #admin=2a0923285184943425d1f53ddd58ec7a
      redhat=a61461431d8a3a52ea041ea5d25dcbc2
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    name: tasks-green-config
